/* Turns a photo into the ASCII art used as the homepage background.

   Run:  npm run ascii
   In:   scripts/source/mir-i-arab.webp
   Out:  src/data/ascii-art.ts  (generated — don't edit by hand, re-run instead)

   How it works:
   1. Crop to the building and shrink to a grid (one pixel = one character).
   2. Remove the sky by colour: pale, unsaturated cells connected to the
      top edge are sky → blank. (Brightness alone fails: the turquoise
      domes are as bright as the sky.)
   3. "Ink" per cell = darkness + edge strength, so tilework, arches and
      outlines read clearly while flat brick stays airy.
   4. Map ink to a character ramp, light → dense. */
import sharp from 'sharp';
import { writeFileSync } from 'node:fs';

const SOURCE = 'scripts/source/mir-i-arab.webp';
const OUT = 'src/data/ascii-art.ts';

// ---- Tuning ---------------------------------------------------------------
const COLS = 180;
// Monospace cells are taller than wide. Matches the canvas cell
// (0.6em wide × 1em tall) so the building isn't stretched.
const CELL_ASPECT = 0.6;
// Crop box in source pixels: the building, a little sky, no square.
const CROP = { left: 0, top: 270, width: 1080, height: 545 };
const RAMP = ' .,:;-=+*#%@';
const EDGE_WEIGHT = 0.7; // how much outlines count vs. darkness
const SKY_SATURATION = 0.2; // below this (and connected to the top) = sky
const DARK_WEIGHT = 1.1;     // how much shadow/tilework counts
const GAMMA = 1.8;
// ---------------------------------------------------------------------------

const ROWS = Math.round((COLS * CROP.height) / CROP.width * CELL_ASPECT);

const { data } = await sharp(SOURCE)
  .extract(CROP)
  .resize(COLS, ROWS, { fit: 'fill', kernel: 'lanczos3' })
  .raw()
  .toBuffer({ resolveWithObject: true });

const clampX = (x) => Math.min(COLS - 1, Math.max(0, x));
const clampY = (y) => Math.min(ROWS - 1, Math.max(0, y));
const rgb = (x, y) => {
  const i = (clampY(y) * COLS + clampX(x)) * 3;
  return [data[i] / 255, data[i + 1] / 255, data[i + 2] / 255];
};
// Perceived brightness, 0–1.
const lum = (x, y) => {
  const [r, g, b] = rgb(x, y);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const saturation = (x, y) => {
  const c = rgb(x, y);
  const max = Math.max(...c);
  return max ? (max - Math.min(...c)) / max : 0;
};

// Sobel edge magnitude, 0–1.
const edge = (x, y) => {
  const gx =
    -lum(x - 1, y - 1) - 2 * lum(x - 1, y) - lum(x - 1, y + 1) +
    lum(x + 1, y - 1) + 2 * lum(x + 1, y) + lum(x + 1, y + 1);
  const gy =
    -lum(x - 1, y - 1) - 2 * lum(x, y - 1) - lum(x + 1, y - 1) +
    lum(x - 1, y + 1) + 2 * lum(x, y + 1) + lum(x + 1, y + 1);
  return Math.min(1, Math.hypot(gx, gy) / 4);
};

// Sky mask: the sky is pale and grey-blue (low saturation); brick, tiles
// and the turquoise domes are all saturated. Flood-fill from the top edge
// through low-saturation cells so nothing inside the building is removed.
const sky = new Uint8Array(COLS * ROWS);
const queue = [];
for (let x = 0; x < COLS; x++) queue.push([x, 0]);
while (queue.length) {
  const [x, y] = queue.pop();
  if (x < 0 || y < 0 || x >= COLS || y >= ROWS) continue;
  const i = y * COLS + x;
  if (sky[i] || saturation(x, y) > SKY_SATURATION) continue;
  sky[i] = 1;
  queue.push([x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]);
}

// Normalise darkness across the building only (the sky would skew it).
let lo = 1, hi = 0;
for (let y = 0; y < ROWS; y++)
  for (let x = 0; x < COLS; x++)
    if (!sky[y * COLS + x]) { const l = lum(x, y); lo = Math.min(lo, l); hi = Math.max(hi, l); }
const darkness = (x, y) => 1 - (lum(x, y) - lo) / (hi - lo || 1);

const lines = [];
for (let y = 0; y < ROWS; y++) {
  let line = '';
  for (let x = 0; x < COLS; x++) {
    if (sky[y * COLS + x]) {
      line += ' ';
      continue;
    }
    // Gamma > 1 keeps most of the facade sparse so only detail stands out.
    const ink = Math.min(1, (darkness(x, y) * DARK_WEIGHT + edge(x, y) * EDGE_WEIGHT) ** GAMMA);
    line += RAMP[Math.round(ink * (RAMP.length - 1))];
  }
  lines.push(line.replace(/\s+$/, ''));
}

const file = `/* GENERATED by scripts/ascii-art.mjs — edit the script, not this file.
   Source: ${SOURCE} · ${COLS}×${ROWS} characters. */
export const asciiArt = {
  cols: ${COLS},
  rows: ${ROWS},
  lines: ${JSON.stringify(lines, null, 2)},
};
`;

writeFileSync(OUT, file);
console.log(lines.join('\n'));
console.log(`\n→ ${OUT} (${COLS}×${ROWS})`);
